CREATE TABLE IF NOT EXISTS categories
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(50)                             NOT NULL,
    CONSTRAINT uq_category_name UNIQUE (name),
    CONSTRAINT pk_category PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS locations
(
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat         FLOAT                                   NOT NULL,
    lon         FLOAT                                   NOT NULL,
    CONSTRAINT pk_location PRIMARY KEY (location_id)
);

CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email   VARCHAR(254)                            NOT NULL,
    name    VARCHAR(250)                            NOT NULL,
    CONSTRAINT uq_user_name UNIQUE (name),
    CONSTRAINT pk_user PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS events
(
    event_id           BIGINT GENERATED BY DEFAULT AS IDENTITY                      NOT NULL,
    annotation         VARCHAR(2000)                                                NOT NULL,
    category_id        BIGINT REFERENCES categories (category_id) ON DELETE CASCADE NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(7000),
    event_date         TIMESTAMP WITHOUT TIME ZONE                                  NOT NULL,
    initiator_id       BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    location_id        BIGINT REFERENCES locations (location_id) ON DELETE CASCADE  NOT NULL,
    paid               BOOLEAN,
    participant_limit  BIGINT,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN,
    state              VARCHAR(50),
    title              VARCHAR(120)                                                 NOT NULL,
    views              BIGINT,
    CONSTRAINT pk_event PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned         BOOLEAN,
    title          VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (compilation_id)
);

CREATE TABLE IF NOT EXISTS participations
(
    participation_id BIGINT GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
    created          TIMESTAMP WITHOUT TIME ZONE                           NOT NULL,
    event_id         BIGINT REFERENCES events (event_id) ON DELETE CASCADE NOT NULL,
    requester_id     BIGINT REFERENCES users (user_id) ON DELETE CASCADE   NOT NULL,
    status           VARCHAR(50)                                           NOT NULL,
    CONSTRAINT pk_participation PRIMARY KEY (participation_id)
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id BIGINT REFERENCES compilations (compilation_id) ON DELETE CASCADE,
    event_id       BIGINT REFERENCES events (event_id)             ON DELETE CASCADE
);