version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: stats_image
    container_name: stats
    ports:
      - "9090:9090"
    depends_on:
    - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_USERNAME=postgres

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stats

  main-service:
    build: main-service
    image: main_service_image
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
    - main-service-db
    - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-service-db:5432/main
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_USERNAME=postgres

  main-service-db:
    image: postgres:14-alpine
    container_name: main-service-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=main
