CREATE TABLE IF NOT EXISTS apps
(
    app_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(200)                            NOT NULL,
    CONSTRAINT pk_app PRIMARY KEY (app_id)
);

CREATE TABLE IF NOT EXISTS hits
(
    hit_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_id  BIGINT REFERENCES apps (app_id)         NOT NULL,
    uri     VARCHAR(200)                            NOT NULL,
    ip      VARCHAR(200)                            NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_hit PRIMARY KEY (hit_id)
);